args: !!python/object:argparse.Namespace
  bs: 1
  cont: false
  cuda: 0
  dataset: MuP
  fp: 16
  inputType: text
  lr: 1.0e-05
  max_input: 1024
  max_output: 512
  model: bart-large-cnn
  num_beams: 5
  num_epoch: 5
  opt: adam
  prototype: 64
  saveData: false
  saveLast: false
  section: abstract+introduction-1
  test: true
spacial_token:
- '[SEP]'
