wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.14.2
    framework: huggingface
    huggingface_version: 4.27.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683518736.233948
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 51
      - 55
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 51
      - 55
      3:
      - 2
      - 7
      - 13
      - 23
      4: 3.8.10
      5: 0.14.2
      6: 4.27.4
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: rouge1
      5: 1
      6:
      - 1
    - 1: rouge2
      5: 1
      6:
      - 1
    - 1: rougeL
      5: 1
      6:
      - 1
model:
  desc: null
  value: bart-large-kg
input_section:
  desc: null
  value: abstract+introduction
input_type:
  desc: null
  value: kg
batch_size:
  desc: null
  value: 4
max_input_length:
  desc: null
  value: 1024
max_output_length:
  desc: null
  value: 512
num_beams:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 1.0e-05
fp:
  desc: null
  value: 16
optimizer:
  desc: null
  value: adam
args/model:
  desc: null
  value: bart-large-kg
args/dataset:
  desc: null
  value: MuP
args/section:
  desc: null
  value: abstract+introduction
args/inputType:
  desc: null
  value: kg
args/prototype:
  desc: null
  value: null
args/max_input:
  desc: null
  value: 1024
args/max_output:
  desc: null
  value: 512
args/bs:
  desc: null
  value: 4
args/num_epoch:
  desc: null
  value: 5
args/num_beams:
  desc: null
  value: 5
args/lr:
  desc: null
  value: 1.0e-05
args/fp:
  desc: null
  value: 16
args/opt:
  desc: null
  value: adam
args/saveLast:
  desc: null
  value: false
args/cont:
  desc: null
  value: false
args/saveData:
  desc: null
  value: false
args/cuda:
  desc: null
  value: 0
spacial_token:
  desc: null
  value:
  - '[Metric]'
  - '[Method]'
  - '[/Material]'
  - '[/Task]'
  - '[PART-OF]'
  - '[USED-FOR]'
  - '[/OtherScientificTerm]'
  - '[/Generic]'
  - '[EVALUATE-FOR]'
  - '[CONJUNCTION]'
  - '[Material]'
  - '[FEATURE-OF]'
  - '[Task]'
  - '[COMPARE]'
  - '[Generic]'
  - '[OtherScientificTerm]'
  - '[HYPONYM-OF]'
  - '[/Method]'
  - '[/Metric]'
train_df:
  desc: null
  value: '       index                                     paper_id                                          input_seq                                         target_seq

    0          0  SP:4d08cdb2de2044bcb574a425b42963b83fbebfbc  [OtherScientificTerm]
    interpolating solutions ...  This paper investigates kernel ridge-less regr...

    1          1  SP:b80bc890180934092cde037b49d94d6e4e06fad9  [OtherScientificTerm]
    episodic memories [/Othe...  This paper presents a novel way of making full...

    2          2  SP:09f2fe6a482bbd6f9bd2c62aa841f995171ba939  [Generic] model [/Generic]
    [USED-FOR] [Generic...  This paper proposes a new framework that compu...

    3          3  SP:a1e2218e6943bf138aeb359e23628676b396ed66  [Method] PID [/Method]
    [CONJUNCTION] [Method] ...  This work proposes a deep reinforcement learni...

    4          4  SP:43e525fb3fa611df7fd44bd3bc9843e57b154c66  [Method] generative
    models [/Method] [USED-FOR...  This paper proposes 3 deep generative models b...

    ...      ...                                          ...                                                ...                                                ...

    18083  18083  SP:0d872fb4321f3a4a3fc61cf4d33b0c7e33f2d695  [Method] deep learning
    [/Method] [CONJUNCTION]...  This paper presents a RNN-RL based method for ...

    18084  18084  SP:4706017e6f8b958c7d0825fed98b285ea2994b59  [Generic] transforms
    [/Generic] [USED-FOR] [Me...  This paper proposes a new pointwise convolutio...

    18085  18085  SP:4706017e6f8b958c7d0825fed98b285ea2994b59  [Generic] transforms
    [/Generic] [USED-FOR] [Me...  This paper presents a new pointwise convolutio...

    18086  18086  SP:63ad3be1dae7ede5c02a847304072c1cbc91b1cb  [OtherScientificTerm]
    dissonance [/OtherScient...  This paper proposes to model various uncertain...

    18087  18087  SP:63ad3be1dae7ede5c02a847304072c1cbc91b1cb  [OtherScientificTerm]
    dissonance [/OtherScient...  The authors proposed a Bayesian graph neural n...


    [18085 rows x 4 columns]'
val_df:
  desc: null
  value: '      index                                     paper_id                                          input_seq                                         target_seq

    0         0  SP:7f4b788b00a2a10bcd60351c3e04c8f597101e96  [Metric] training performance
    [/Metric] [CONJU...  This paper studies FL under local differential...

    1         1  SP:7f4b788b00a2a10bcd60351c3e04c8f597101e96  [Metric] training performance
    [/Metric] [CONJU...  This paper studies a low communication algorit...

    2         2  SP:7f4b788b00a2a10bcd60351c3e04c8f597101e96  [Metric] training performance
    [/Metric] [CONJU...  The paper proposed a differentially private tr...

    3         3  SP:632666b52c7c551d67fbbe70c06ed589c3a5e187  [OtherScientificTerm]
    prior knowledge [/OtherS...  This submission works on the neural machine tr...

    4         4  SP:632666b52c7c551d67fbbe70c06ed589c3a5e187  [OtherScientificTerm]
    prior knowledge [/OtherS...  This paper proposes a method to introduce **pr...

    ...     ...                                          ...                                                ...                                                ...

    3599   3599  SP:18aaba3423e81e9437b509d1a5e24836ef5635f6  [Material] time - series
    [/Material] [USED-FOR...  This paper defines a set of learnable basis fu...

    3600   3600  SP:18aaba3423e81e9437b509d1a5e24836ef5635f6  [Material] time - series
    [/Material] [USED-FOR...  A typical Wavelet Transform is built through t...

    3601   3601  SP:3058e6bc5e8c62af325c214c9e1436d6cdf09204  [OtherScientificTerm]
    Euclidean geometry [/Oth...  This paper builds a new graph convolutional ne...

    3602   3602  SP:3058e6bc5e8c62af325c214c9e1436d6cdf09204  [OtherScientificTerm]
    Euclidean geometry [/Oth...  The authors propose using non-Euclidean spaces...

    3603   3603  SP:3058e6bc5e8c62af325c214c9e1436d6cdf09204  [OtherScientificTerm]
    Euclidean geometry [/Oth...  In this paper, the authors address representat...


    [3604 rows x 4 columns]'
