wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.14.2
    framework: huggingface
    huggingface_version: 4.27.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1683213961.268264
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 51
      - 55
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 51
      - 55
      3:
      - 2
      - 7
      - 13
      - 23
      4: 3.8.10
      5: 0.14.2
      6: 4.27.4
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: train_loss
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: rouge1
      5: 1
      6:
      - 1
    - 1: rouge2
      5: 1
      6:
      - 1
    - 1: rougeL
      5: 1
      6:
      - 1
model:
  desc: null
  value: bart-large
input_section:
  desc: null
  value: abstract
input_type:
  desc: null
  value: kg
batch_size:
  desc: null
  value: 8
max_input_length:
  desc: null
  value: 355
max_output_length:
  desc: null
  value: 512
num_beams:
  desc: null
  value: 3
learning_rate:
  desc: null
  value: 1.0e-05
fp:
  desc: null
  value: 16
optimizer:
  desc: null
  value: adam
args/model:
  desc: null
  value: bart-large
args/dataset:
  desc: null
  value: arXiv
args/section:
  desc: null
  value: abstract
args/inputType:
  desc: null
  value: kg
args/prototype:
  desc: null
  value: null
args/max_input:
  desc: null
  value: 355
args/max_output:
  desc: null
  value: 512
args/bs:
  desc: null
  value: 8
args/num_epoch:
  desc: null
  value: 3
args/num_beams:
  desc: null
  value: 3
args/lr:
  desc: null
  value: 1.0e-05
args/fp:
  desc: null
  value: 16
args/opt:
  desc: null
  value: adam
args/saveData:
  desc: null
  value: false
args/cuda:
  desc: null
  value: 0
spacial_token:
  desc: null
  value:
  - '[Metric]'
  - '[Method]'
  - '[/Material]'
  - '[/Task]'
  - '[PART-OF]'
  - '[USED-FOR]'
  - '[/OtherScientificTerm]'
  - '[/Generic]'
  - '[EVALUATE-FOR]'
  - '[CONJUNCTION]'
  - '[Material]'
  - '[FEATURE-OF]'
  - '[Task]'
  - '[COMPARE]'
  - '[Generic]'
  - '[OtherScientificTerm]'
  - '[HYPONYM-OF]'
  - '[/Method]'
  - '[/Metric]'
train_df:
  desc: null
  value: '               paper_id                                          input_seq                                         target_seq

    0             1405.3379  [Metric] learning rates [/Metric] [USED-FOR] [...  additive
    models play an important role in semi...

    1             0901.1147  [OtherScientificTerm] @xmath3 peak production ...  we
    have studied the leptonic decay @xmath0 , v...

    2           nlin0608019  [OtherScientificTerm] current [/OtherScientifi...  in
    84 , 258 ( 2000 ) , mateos conjectured that...

    3             0903.5449  [Method] random phase diffuser [/Method] [USED...  the
    effect of a random phase diffuser on fluct...

    4         hep-ph0605279  [OtherScientificTerm] @xmath0 - th @xmath1 - m...  with
    a special intention of clarifying the und...

    ...                 ...                                                ...                                                ...

    200999  quant-ph0402038  [Method] classical strategies [/Method] [USED-...  effects
    of a corrupt source on the dynamics of...

    201000        0907.3736  [Method] exact diagonalization [/Method] [CONJ...  we
    compute the entropy of antiferromagnetic qu...

    201001       1506.04688  [Method] quotient - polynomial graph [/Method]...  as
    a generalization of orbit - polynomial and ...

    201002  cond-mat0304118  [Method] solid state devices [/Method] [USED-F...  within
    the lowest - order born approximation ,...

    201003        0801.2228  [OtherScientificTerm] filler particles [/Other...  conducting
    submicron particles are well - suit...


    [201004 rows x 3 columns]'
val_df:
  desc: null
  value: '             paper_id                                          input_seq                                         target_seq

    0           0708.1996  [OtherScientificTerm] strong anchoring [/Other...    we
    study the phase behavior of a nematic liq...

    1           0709.1158  [OtherScientificTerm] scaling relations [/Othe...    determining
    the scaling relations between ga...

    2           1112.4795  [OtherScientificTerm] spatial quantum correlat...    we
    show how to control spatial quantum corre...

    3           1012.5771  [OtherScientificTerm] shock - excited environm...    class   i
    methanol masers are believed to be...

    4          1601.06075  [Material] physics publications [/Material] [C...    nowadays
    , scientific challenges usually req...

    ...               ...                                                ...                                                ...

    6431    hep-th0504088  [OtherScientificTerm] weak gauge - invariance ...    we
    give a formal proof that the space - time...

    6432       1505.07898  [Method] long wave approximation [/Method] [FE...    we
    consider here the effects of inertia on t...

    6433       1607.05481  [OtherScientificTerm] local potential [/OtherS...    we
    introduce an orbital - optimized double -...

    6434       1703.05742  [Method] optical resonant cavities [/Method] [...    we
    have been developing optical resonant cav...

    6435  cond-mat9402061  [OtherScientificTerm] magnetic order parameter...    we
    have performed a numerical investigation ...


    [6436 rows x 3 columns]'
