args: !!python/object:argparse.Namespace
  bs: 8
  cluster: KNN-k3
  cont: false
  cuda: 0
  dataset: MuP
  fp: 16
  genSum: val
  inputType: text
  lr: 1.0e-05
  max_input: 369
  max_output: 512
  model: bart-large-cnn
  num_beams: 5
  num_epoch: 5
  opt: adam
  prototype: 16
  saveData: false
  saveLast: false
  section: abstract
spacial_token: null
