wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.14.2
    framework: huggingface
    huggingface_version: 4.27.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682908197.966091
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      3:
      - 2
      - 7
      - 13
      - 23
      4: 3.8.10
      5: 0.14.2
      6: 4.27.4
      8:
      - 5
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: rouge_1
      5: 1
      6:
      - 1
    - 1: rouge_2
      5: 1
      6:
      - 1
    - 1: rouge_l
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
model:
  desc: null
  value: bart-large-cnn
input_section:
  desc: null
  value: abstract
input_type:
  desc: null
  value: text
batch_size:
  desc: null
  value: 8
max_input_length:
  desc: null
  value: 512
max_output_length:
  desc: null
  value: 512
num_beams:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 1.0e-05
fp:
  desc: null
  value: 32
optimizer:
  desc: null
  value: adam
